-- Phylo: common food species seed
-- Run in the Supabase SQL editor.
--
-- Skips species already present (case-insensitive latin_name), matching index
-- species_latin_name_unique on lower(trim(latin_name)).
--
-- Cultivar/subspecies entries are separate where noted; same-species foods are
-- merged with alternative_names (e.g. portobello + button mushroom, edamame + soybean).

INSERT INTO public.species (common_name, latin_name, category, alternative_names)
SELECT v.common_name, v.latin_name, v.category, v.alternative_names
FROM (
  VALUES
    -- ── Plants: vegetables ───────────────────────────────────────────────────
    ('Carrot', 'Daucus carota', 'plant', ARRAY['carrots', 'baby carrot']::text[]),
    ('Spinach', 'Spinacia oleracea', 'plant', ARRAY['baby spinach', 'leaf spinach']::text[]),
    ('Kale', 'Brassica oleracea var. sabellica', 'plant', ARRAY['curly kale', 'lacinato kale', 'dinosaur kale', 'Tuscan kale']::text[]),
    ('Broccoli', 'Brassica oleracea var. italica', 'plant', ARRAY['broccoli florets', 'broccolini']::text[]),
    ('Cauliflower', 'Brassica oleracea var. botrytis', 'plant', ARRAY['cauliflower florets', 'cauliflower rice']::text[]),
    ('Brussels sprouts', 'Brassica oleracea var. gemmifera', 'plant', ARRAY['brussel sprouts', 'Brussels sprout']::text[]),
    ('Kohlrabi', 'Brassica oleracea var. gongylodes', 'plant', ARRAY['kohlrabi bulb', 'German turnip']::text[]),
    ('Cabbage', 'Brassica oleracea var. capitata', 'plant', ARRAY['green cabbage', 'red cabbage', 'napa cabbage', 'savoy cabbage']::text[]),
    ('Collard greens', 'Brassica oleracea var. viridis', 'plant', ARRAY['collards', 'collard']::text[]),
    ('Bok choy', 'Brassica rapa subsp. chinensis', 'plant', ARRAY['pak choi', 'bok choi', 'Chinese cabbage', 'baby bok choy']::text[]),
    ('Turnip', 'Brassica rapa subsp. rapa', 'plant', ARRAY['turnips', 'turnip greens']::text[]),
    ('Sweet potato', 'Ipomoea batatas', 'plant', ARRAY['sweet potatoes', 'yam (US)', 'garnet yam', 'jewel yam']::text[]),
    ('Yam', 'Dioscorea alata', 'plant', ARRAY['true yam', 'purple yam', 'ube', 'water yam']::text[]),
    ('Potato', 'Solanum tuberosum', 'plant', ARRAY['potatoes', 'russet potato', 'Yukon gold', 'red potato', 'new potato']::text[]),
    ('Tomato', 'Solanum lycopersicum', 'plant', ARRAY['tomatoes', 'cherry tomato', 'roma tomato', 'grape tomato']::text[]),
    ('Bell pepper', 'Capsicum annuum', 'plant', ARRAY['sweet pepper', 'red pepper', 'green pepper', 'yellow pepper', 'chili pepper', 'chilli', 'chile', 'jalapeño', 'jalapeno', 'serrano', 'poblano', 'anaheim pepper', 'paprika', 'cayenne', 'hot pepper']::text[]),
    ('Eggplant', 'Solanum melongena', 'plant', ARRAY['aubergine', 'eggplants', 'Japanese eggplant']::text[]),
    ('Zucchini', 'Cucurbita pepo var. cylindrica', 'plant', ARRAY['courgette', 'summer squash', 'zucchinis']::text[]),
    ('Cucumber', 'Cucumis sativus', 'plant', ARRAY['cucumbers', 'English cucumber', 'Persian cucumber', 'pickle', 'gherkin']::text[]),
    ('Pumpkin', 'Cucurbita maxima', 'plant', ARRAY['pumpkins', 'sugar pumpkin', 'pie pumpkin', 'pumpkin seed', 'pumpkin seeds']::text[]),
    ('Butternut squash', 'Cucurbita moschata', 'plant', ARRAY['butternut', 'winter squash']::text[]),
    ('Acorn squash', 'Cucurbita pepo var. turbinata', 'plant', ARRAY['acorn', 'pepper squash']::text[]),
    ('Spaghetti squash', 'Cucurbita pepo var. pepo', 'plant', ARRAY['vegetable spaghetti', 'spaghetti squash noodles']::text[]),
    ('Beet', 'Beta vulgaris', 'plant', ARRAY['beetroot', 'beets', 'Swiss chard', 'chard', 'silverbeet', 'beet greens']::text[]),
    ('Radish', 'Raphanus sativus', 'plant', ARRAY['radishes', 'daikon', 'red radish']::text[]),
    ('Parsnip', 'Pastinaca sativa', 'plant', ARRAY['parsnips']::text[]),
    ('Celery', 'Apium graveolens', 'plant', ARRAY['celery stalk', 'celery stick', 'celeriac']::text[]),
    ('Fennel', 'Foeniculum vulgare', 'plant', ARRAY['fennel bulb', 'finocchio', 'fennel seed', 'fennel seeds']::text[]),
    ('Artichoke', 'Cynara cardunculus var. scolymus', 'plant', ARRAY['globe artichoke', 'artichoke hearts']::text[]),
    ('Asparagus', 'Asparagus officinalis', 'plant', ARRAY['asparagus spears', 'white asparagus']::text[]),
    ('Leek', 'Allium ampeloprasum var. porrum', 'plant', ARRAY['leeks']::text[]),
    ('Green onion', 'Allium fistulosum', 'plant', ARRAY['scallion', 'scallions', 'spring onion', 'spring onions']::text[]),
    ('Onion', 'Allium cepa', 'plant', ARRAY['onions', 'yellow onion', 'red onion', 'white onion', 'sweet onion']::text[]),
    ('Shallot', 'Allium cepa var. aggregatum', 'plant', ARRAY['shallots', 'eschalot']::text[]),
    ('Garlic', 'Allium sativum', 'plant', ARRAY['garlic clove', 'garlic cloves', 'roasted garlic']::text[]),
    ('Corn', 'Zea mays', 'plant', ARRAY['maize', 'sweet corn', 'corn on the cob', 'cornmeal', 'polenta', 'hominy', 'corn kernel']::text[]),
    ('Pea', 'Pisum sativum', 'plant', ARRAY['peas', 'green pea', 'garden pea', 'split pea', 'split peas', 'snow pea', 'snap pea']::text[]),
    ('Green bean', 'Phaseolus vulgaris', 'plant', ARRAY['green beans', 'string bean', 'snap bean', 'haricot vert', 'black bean', 'black beans', 'pinto bean', 'pinto beans', 'kidney bean', 'kidney beans', 'navy bean', 'navy beans', 'cannellini bean', 'cannellini beans', 'great northern bean']::text[]),
    ('Soybean', 'Glycine max', 'plant', ARRAY['soy', 'soybeans', 'edamame', 'soya bean', 'soya']::text[]),
    ('Okra', 'Abelmoschus esculenta', 'plant', ARRAY['okra pods', 'lady finger', 'gumbo']::text[]),
    ('Arugula', 'Eruca vesicaria', 'plant', ARRAY['rocket', 'salad rocket', 'rucola']::text[]),

    -- ── Plants: fruits ───────────────────────────────────────────────────────
    ('Apple', 'Malus domestica', 'plant', ARRAY['apples', 'Gala apple', 'Granny Smith', 'Fuji apple']::text[]),
    ('Pear', 'Pyrus communis', 'plant', ARRAY['pears', 'Bartlett pear', 'Anjou pear']::text[]),
    ('Peach', 'Prunus persica', 'plant', ARRAY['peaches', 'nectarine', 'nectarines', 'white peach']::text[]),
    ('Plum', 'Prunus domestica', 'plant', ARRAY['plums', 'prune', 'prunes', 'dried plum']::text[]),
    ('Apricot', 'Prunus armeniaca', 'plant', ARRAY['apricots', 'dried apricot']::text[]),
    ('Cherry', 'Prunus avium', 'plant', ARRAY['cherries', 'sweet cherry', 'sour cherry', 'Bing cherry']::text[]),
    ('Strawberry', 'Fragaria × ananassa', 'plant', ARRAY['strawberries']::text[]),
    ('Raspberry', 'Rubus idaeus', 'plant', ARRAY['raspberries', 'red raspberry']::text[]),
    ('Blackberry', 'Rubus fruticosus', 'plant', ARRAY['blackberries']::text[]),
    ('Blueberry', 'Vaccinium corymbosum', 'plant', ARRAY['blueberries', 'highbush blueberry']::text[]),
    ('Cranberry', 'Vaccinium macrocarpon', 'plant', ARRAY['cranberries', 'dried cranberry', 'cranberry sauce']::text[]),
    ('Grape', 'Vitis vinifera', 'plant', ARRAY['grapes', 'red grape', 'green grape', 'raisin', 'raisins']::text[]),
    ('Watermelon', 'Citrullus lanatus', 'plant', ARRAY['watermelons']::text[]),
    ('Cantaloupe', 'Cucumis melo', 'plant', ARRAY['cantaloupes', 'honeydew', 'honeydew melon', 'muskmelon', 'melon', 'galia melon']::text[]),
    ('Orange', 'Citrus × sinensis', 'plant', ARRAY['oranges', 'navel orange', 'blood orange', 'cara cara']::text[]),
    ('Lemon', 'Citrus limon', 'plant', ARRAY['lemons', 'Meyer lemon']::text[]),
    ('Lime', 'Citrus aurantiifolia', 'plant', ARRAY['limes', 'key lime', 'Persian lime']::text[]),
    ('Grapefruit', 'Citrus × paradisi', 'plant', ARRAY['grapefruits', 'pink grapefruit', 'ruby red grapefruit']::text[]),
    ('Tangerine', 'Citrus reticulata', 'plant', ARRAY['tangerines', 'mandarin', 'mandarin orange', 'clementine', 'satsuma']::text[]),
    ('Banana', 'Musa × paradisiaca', 'plant', ARRAY['bananas', 'plantain', 'plantains']::text[]),
    ('Mango', 'Mangifera indica', 'plant', ARRAY['mangoes', 'mangos', 'Ataulfo mango']::text[]),
    ('Papaya', 'Carica papaya', 'plant', ARRAY['papayas', 'pawpaw']::text[]),
    ('Pineapple', 'Ananas comosus', 'plant', ARRAY['pineapples']::text[]),
    ('Kiwi', 'Actinidia deliciosa', 'plant', ARRAY['kiwifruit', 'kiwis', 'Chinese gooseberry']::text[]),
    ('Fig', 'Ficus carica', 'plant', ARRAY['figs', 'dried fig']::text[]),
    ('Pomegranate', 'Punica granatum', 'plant', ARRAY['pomegranates', 'pomegranate seeds']::text[]),
    ('Lychee', 'Litchi chinensis', 'plant', ARRAY['lychees', 'litchi']::text[]),
    ('Dragon fruit', 'Hylocereus undatus', 'plant', ARRAY['pitaya', 'pitahaya', 'dragonfruit']::text[]),
    ('Passion fruit', 'Passiflora edulis', 'plant', ARRAY['passionfruit', 'maracuja']::text[]),
    ('Guava', 'Psidium guajava', 'plant', ARRAY['guavas']::text[]),
    ('Jackfruit', 'Artocarpus heterophyllus', 'plant', ARRAY['jackfruits', 'young jackfruit']::text[]),
    ('Durian', 'Durio zibethinus', 'plant', ARRAY['durians']::text[]),
    ('Avocado', 'Persea americana', 'plant', ARRAY['avocados', 'Haas avocado', 'Hass avocado', 'guacamole']::text[]),
    ('Olive', 'Olea europaea', 'plant', ARRAY['olives', 'black olive', 'green olive', 'Kalamata olive', 'olive oil']::text[]),
    ('Coconut', 'Cocos nucifera', 'plant', ARRAY['coconuts', 'coconut meat', 'coconut milk', 'coconut water', 'shredded coconut']::text[]),
    ('Date', 'Phoenix dactylifera', 'plant', ARRAY['dates', 'Medjool date', 'dried date']::text[]),
    ('Persimmon', 'Diospyros kaki', 'plant', ARRAY['persimmons', 'Fuyu persimmon', 'Hachiya persimmon']::text[]),
    ('Quince', 'Cydonia oblonga', 'plant', ARRAY['quinces']::text[]),
    ('Loquat', 'Eriobotrya japonica', 'plant', ARRAY['loquats', 'Japanese plum']::text[]),
    ('Prickly pear', 'Opuntia ficus-indica', 'plant', ARRAY['cactus pear', 'nopal fruit', 'tuna fruit']::text[]),
    ('Starfruit', 'Averrhoa carambola', 'plant', ARRAY['carambola', 'star fruit']::text[]),
    ('Tamarind', 'Tamarindus indica', 'plant', ARRAY['tamarind paste', 'tamarind pulp']::text[]),

    -- ── Plants: grains and legumes ─────────────────────────────────────────
    ('Wheat', 'Triticum aestivum', 'plant', ARRAY['wheat berry', 'wheat berries', 'whole wheat', 'bulgur', 'semolina', 'farro', 'spelt']::text[]),
    ('Rice', 'Oryza sativa', 'plant', ARRAY['brown rice', 'white rice', 'jasmine rice', 'basmati rice', 'wild rice blend', 'arborio rice']::text[]),
    ('Oat', 'Avena sativa', 'plant', ARRAY['oats', 'oatmeal', 'rolled oats', 'steel cut oats', 'porridge', 'granola']::text[]),
    ('Barley', 'Hordeum vulgare', 'plant', ARRAY['pearl barley', 'hulled barley', 'barley grain']::text[]),
    ('Rye', 'Secale cereale', 'plant', ARRAY['rye grain', 'rye berry', 'rye bread grain']::text[]),
    ('Millet', 'Panicum miliaceum', 'plant', ARRAY['proso millet', 'millet grain']::text[]),
    ('Sorghum', 'Sorghum bicolor', 'plant', ARRAY['sorghum grain', 'milo']::text[]),
    ('Quinoa', 'Chenopodium quinoa', 'plant', ARRAY['quinoa grain', 'white quinoa', 'red quinoa']::text[]),
    ('Amaranth', 'Amaranthus caudatus', 'plant', ARRAY['amaranth grain', 'amaranth seed']::text[]),
    ('Buckwheat', 'Fagopyrum esculentum', 'plant', ARRAY['buckwheat groats', 'kasha', 'soba grain']::text[]),
    ('Teff', 'Eragrostis tef', 'plant', ARRAY['teff grain', 'teff flour']::text[]),
    ('Chickpea', 'Cicer arietinum', 'plant', ARRAY['chickpeas', 'garbanzo bean', 'garbanzo beans', 'chana']::text[]),
    ('Lentil', 'Lens culinaris', 'plant', ARRAY['lentils', 'green lentil', 'green lentils', 'red lentil', 'red lentils', 'brown lentil', 'dal']::text[]),
    ('Peanut', 'Arachis hypogaea', 'plant', ARRAY['peanuts', 'groundnut', 'groundnuts', 'peanut butter']::text[]),
    ('Fava bean', 'Vicia faba', 'plant', ARRAY['fava beans', 'broad bean', 'broad beans', 'fava']::text[]),
    ('Mung bean', 'Vigna radiata', 'plant', ARRAY['mung beans', 'moong bean', 'bean sprouts', 'mung bean sprouts']::text[]),
    ('Adzuki bean', 'Vigna angularis', 'plant', ARRAY['adzuki beans', 'azuki bean', 'red bean (Asian)']::text[]),
    ('Black-eyed pea', 'Vigna unguiculata subsp. unguiculata', 'plant', ARRAY['black-eyed peas', 'cowpea', 'cowpeas', 'southern pea']::text[]),

    -- ── Plants: nuts and seeds ─────────────────────────────────────────────
    ('Almond', 'Prunus dulcis', 'plant', ARRAY['almonds', 'almond butter', 'almond milk', 'marcona almond']::text[]),
    ('Walnut', 'Juglans regia', 'plant', ARRAY['walnuts', 'English walnut', 'black walnut']::text[]),
    ('Pecan', 'Carya illinoinensis', 'plant', ARRAY['pecans', 'pecan halves']::text[]),
    ('Cashew', 'Anacardium occidentale', 'plant', ARRAY['cashews', 'cashew nut', 'cashew nuts']::text[]),
    ('Pistachio', 'Pistacia vera', 'plant', ARRAY['pistachios', 'pistachio nut']::text[]),
    ('Macadamia', 'Macadamia integrifolia', 'plant', ARRAY['macadamia nut', 'macadamia nuts', 'macadamias']::text[]),
    ('Brazil nut', 'Bertholletia excelsa', 'plant', ARRAY['Brazil nuts', 'brazil nut']::text[]),
    ('Hazelnut', 'Corylus avellana', 'plant', ARRAY['hazelnuts', 'filbert', 'filberts']::text[]),
    ('Chestnut', 'Castanea sativa', 'plant', ARRAY['chestnuts', 'sweet chestnut', 'roasted chestnut']::text[]),
    ('Pine nut', 'Pinus pinea', 'plant', ARRAY['pine nuts', 'pignoli', 'pignolia']::text[]),
    ('Sunflower seed', 'Helianthus annuus', 'plant', ARRAY['sunflower seeds', 'sunflower kernels']::text[]),
    ('Sesame seed', 'Sesamum indicum', 'plant', ARRAY['sesame seeds', 'sesame', 'tahini']::text[]),
    ('Flaxseed', 'Linum usitatissimum', 'plant', ARRAY['flax seed', 'flax seeds', 'linseed', 'ground flax']::text[]),
    ('Chia seed', 'Salvia hispanica', 'plant', ARRAY['chia seeds', 'chia']::text[]),
    ('Hemp seed', 'Cannabis sativa', 'plant', ARRAY['hemp seeds', 'hemp hearts', 'hulled hemp seed']::text[]),
    ('Poppy seed', 'Papaver somniferum', 'plant', ARRAY['poppy seeds']::text[]),

    -- ── Plants: herbs and spices ───────────────────────────────────────────
    ('Basil', 'Ocimum basilicum', 'plant', ARRAY['sweet basil', 'Thai basil', 'Genovese basil']::text[]),
    ('Oregano', 'Origanum vulgare', 'plant', ARRAY['dried oregano', 'Mexican oregano']::text[]),
    ('Thyme', 'Thymus vulgaris', 'plant', ARRAY['fresh thyme', 'dried thyme', 'lemon thyme']::text[]),
    ('Rosemary', 'Salvia rosmarinus', 'plant', ARRAY['fresh rosemary', 'dried rosemary']::text[]),
    ('Sage', 'Salvia officinalis', 'plant', ARRAY['fresh sage', 'dried sage']::text[]),
    ('Mint', 'Mentha spicata', 'plant', ARRAY['spearmint', 'peppermint', 'fresh mint', 'mint leaves']::text[]),
    ('Cilantro', 'Coriandrum sativum', 'plant', ARRAY['coriander', 'coriander leaf', 'coriander leaves', 'coriander seed', 'coriander seeds', 'Chinese parsley']::text[]),
    ('Parsley', 'Petroselinum crispum', 'plant', ARRAY['flat-leaf parsley', 'curly parsley', 'Italian parsley']::text[]),
    ('Dill', 'Anethum graveolens', 'plant', ARRAY['dill weed', 'dill fronds', 'dill seed']::text[]),
    ('Tarragon', 'Artemisia dracunculus', 'plant', ARRAY['French tarragon', 'fresh tarragon']::text[]),
    ('Chives', 'Allium schoenoprasum', 'plant', ARRAY['chive', 'fresh chives']::text[]),
    ('Bay leaf', 'Laurus nobilis', 'plant', ARRAY['bay leaves', 'laurel leaf', 'laurel leaves']::text[]),
    ('Lemongrass', 'Cymbopogon citratus', 'plant', ARRAY['lemongrass stalk', 'lemon grass']::text[]),
    ('Turmeric', 'Curcuma longa', 'plant', ARRAY['turmeric root', 'fresh turmeric', 'ground turmeric']::text[]),
    ('Ginger', 'Zingiber officinale', 'plant', ARRAY['ginger root', 'fresh ginger', 'ground ginger']::text[]),
    ('Galangal', 'Alpinia galanga', 'plant', ARRAY['Thai galangal', 'greater galangal']::text[]),
    ('Black pepper', 'Piper nigrum', 'plant', ARRAY['peppercorn', 'peppercorns', 'white pepper', 'ground pepper', 'black peppercorn']::text[]),
    ('Cardamom', 'Elettaria cardamomum', 'plant', ARRAY['green cardamom', 'cardamom pod', 'cardamom pods']::text[]),
    ('Cinnamon', 'Cinnamomum verum', 'plant', ARRAY['Ceylon cinnamon', 'cinnamon stick', 'cinnamon sticks', 'ground cinnamon']::text[]),
    ('Clove', 'Syzygium aromaticum', 'plant', ARRAY['cloves', 'whole clove', 'ground clove']::text[]),
    ('Nutmeg', 'Myristica fragrans', 'plant', ARRAY['ground nutmeg', 'nutmeg seed', 'mace']::text[]),
    ('Allspice', 'Pimenta dioica', 'plant', ARRAY['allspice berry', 'Jamaica pepper']::text[]),
    ('Star anise', 'Illicium verum', 'plant', ARRAY['star anise pod', 'Chinese star anise']::text[]),
    ('Cumin', 'Cuminum cyminum', 'plant', ARRAY['cumin seed', 'cumin seeds', 'ground cumin']::text[]),
    ('Mustard seed', 'Brassica juncea', 'plant', ARRAY['mustard seeds', 'brown mustard seed', 'yellow mustard seed']::text[]),
    ('Fenugreek', 'Trigonella foenum-graecum', 'plant', ARRAY['fenugreek seed', 'fenugreek seeds', 'methi']::text[]),
    ('Vanilla', 'Vanilla planifolia', 'plant', ARRAY['vanilla bean', 'vanilla beans', 'vanilla extract']::text[]),
    ('Saffron', 'Crocus sativus', 'plant', ARRAY['saffron threads', 'saffron stigma']::text[]),
    ('Sumac', 'Rhus coriaria', 'plant', ARRAY['sumac spice', 'ground sumac']::text[]),

    -- ── Plants: other ──────────────────────────────────────────────────────
    ('Coffee', 'Coffea arabica', 'plant', ARRAY['coffee bean', 'coffee beans', 'espresso bean']::text[]),
    ('Cacao', 'Theobroma cacao', 'plant', ARRAY['cocoa', 'cocoa bean', 'cocoa beans', 'cacao bean', 'cacao nibs', 'chocolate']::text[]),
    ('Tea', 'Camellia sinensis', 'plant', ARRAY['green tea', 'black tea', 'white tea', 'oolong tea', 'tea leaf', 'tea leaves']::text[]),
    ('Sugar cane', 'Saccharum officinarum', 'plant', ARRAY['sugarcane', 'cane sugar', 'raw sugar']::text[]),
    ('Agave', 'Agave tequilana', 'plant', ARRAY['agave nectar', 'agave syrup', 'blue agave']::text[]),
    ('Stevia', 'Stevia rebaudiana', 'plant', ARRAY['stevia leaf', 'stevia sweetener']::text[]),
    ('Moringa', 'Moringa oleifera', 'plant', ARRAY['moringa leaf', 'moringa leaves', 'drumstick tree leaf']::text[]),
    ('Spirulina', 'Arthrospira platensis', 'other', ARRAY['spirulina powder', 'blue-green algae supplement']::text[]),

    -- ── Animals ────────────────────────────────────────────────────────────
    ('Chicken', 'Gallus gallus domesticus', 'animal', ARRAY['poultry', 'hen', 'rooster', 'chicken breast', 'chicken thigh', 'chicken wing', 'chicken drumstick', 'ground chicken', 'egg', 'eggs']::text[]),
    ('Cow', 'Bos taurus', 'animal', ARRAY['beef', 'steak', 'ground beef', 'veal', 'brisket', 'ribs', 'milk', 'butter', 'cheese', 'dairy', 'hamburger', 'burger', 'roast beef']::text[]),
    ('Pig', 'Sus scrofa domesticus', 'animal', ARRAY['pork', 'bacon', 'ham', 'sausage', 'prosciutto', 'pancetta', 'ground pork', 'pork chop', 'pork loin']::text[]),
    ('Lamb', 'Ovis aries', 'animal', ARRAY['lamb chop', 'lamb chops', 'lamb shank', 'mutton', 'ground lamb', 'lamb leg']::text[]),
    ('Goat', 'Capra aegagrus hircus', 'animal', ARRAY['goat meat', 'chevon', 'goat cheese', 'goat milk']::text[]),
    ('Turkey', 'Meleagris gallopavo', 'animal', ARRAY['turkey breast', 'ground turkey', 'turkey leg', 'turkey thigh']::text[]),
    ('Duck', 'Anas platyrhynchos domesticus', 'animal', ARRAY['duck breast', 'duck leg', 'Peking duck', 'duck confit']::text[]),
    ('Rabbit', 'Oryctolagus cuniculus', 'animal', ARRAY['rabbit meat', 'lapin']::text[]),
    ('Bison', 'Bison bison', 'animal', ARRAY['bison meat', 'buffalo meat', 'American bison']::text[]),
    ('Venison', 'Odocoileus virginianus', 'animal', ARRAY['deer', 'white-tailed deer', 'deer meat']::text[]),
    ('Elk', 'Cervus canadensis', 'animal', ARRAY['elk meat', 'wapiti']::text[]),
    ('Atlantic salmon', 'Salmo salar', 'animal', ARRAY['salmon', 'salmon fillet', 'smoked salmon', 'lox']::text[]),
    ('Sockeye salmon', 'Oncorhynchus nerka', 'animal', ARRAY['red salmon', 'sockeye', 'wild sockeye']::text[]),
    ('Yellowfin tuna', 'Thunnus albacares', 'animal', ARRAY['tuna', 'ahi tuna', 'ahi', 'yellowfin', 'tuna steak']::text[]),
    ('Bluefin tuna', 'Thunnus thynnus', 'animal', ARRAY['bluefin', 'toro', 'hon maguro']::text[]),
    ('Cod', 'Gadus morhua', 'animal', ARRAY['Atlantic cod', 'cod fillet', 'salt cod', 'bacalao']::text[]),
    ('Tilapia', 'Oreochromis niloticus', 'animal', ARRAY['tilapia fillet', 'St. Peter''s fish']::text[]),
    ('Catfish', 'Ictalurus punctatus', 'animal', ARRAY['channel catfish', 'catfish fillet']::text[]),
    ('Rainbow trout', 'Oncorhynchus mykiss', 'animal', ARRAY['trout', 'trout fillet', 'steelhead']::text[]),
    ('Sardine', 'Sardina pilchardus', 'animal', ARRAY['sardines', 'pilchard', 'pilchards']::text[]),
    ('Anchovy', 'Engraulis encrasicolus', 'animal', ARRAY['anchovies', 'boquerones']::text[]),
    ('Atlantic mackerel', 'Scomber scombrus', 'animal', ARRAY['mackerel', 'mackerel fillet']::text[]),
    ('Atlantic herring', 'Clupea harengus', 'animal', ARRAY['herring', 'pickled herring', 'kippers']::text[]),
    ('Atlantic halibut', 'Hippoglossus hippoglossus', 'animal', ARRAY['halibut', 'halibut fillet', 'halibut steak']::text[]),
    ('European sea bass', 'Dicentrarchus labrax', 'animal', ARRAY['sea bass', 'branzino', 'loup de mer']::text[]),
    ('Mahi-mahi', 'Coryphaena hippurus', 'animal', ARRAY['dolphinfish', 'dorado', 'mahi mahi']::text[]),
    ('Swordfish', 'Xiphias gladius', 'animal', ARRAY['swordfish steak', 'swordfish fillet']::text[]),
    ('Whiteleg shrimp', 'Litopenaeus vannamei', 'animal', ARRAY['shrimp', 'shrimps', 'prawn', 'prawns', 'jumbo shrimp']::text[]),
    ('Blue crab', 'Callinectes sapidus', 'animal', ARRAY['crab', 'crab meat', 'crab cake', 'soft shell crab']::text[]),
    ('American lobster', 'Homarus americanus', 'animal', ARRAY['lobster', 'lobster tail', 'lobster meat']::text[]),
    ('Hard clam', 'Mercenaria mercenaria', 'animal', ARRAY['clam', 'clams', 'quahog', 'chowder clam', 'littleneck clam']::text[]),
    ('Eastern oyster', 'Crassostrea virginica', 'animal', ARRAY['oyster', 'oysters', 'raw oyster']::text[]),
    ('Blue mussel', 'Mytilus edulis', 'animal', ARRAY['mussel', 'mussels', 'mussels mariniere']::text[]),
    ('Sea scallop', 'Placopecten magellanicus', 'animal', ARRAY['scallop', 'scallops', 'bay scallop', 'sea scallops']::text[]),
    ('Longfin squid', 'Doryteuthis pealeii', 'animal', ARRAY['squid', 'calamari', 'squid rings']::text[]),
    ('Common octopus', 'Octopus vulgaris', 'animal', ARRAY['octopus', 'pulpo', 'octopus tentacle']::text[]),
    ('Honey bee', 'Apis mellifera', 'animal', ARRAY['honey', 'raw honey', 'bee honey', 'wildflower honey']::text[]),

    -- ── Fungi ────────────────────────────────────────────────────────────────
    ('Shiitake', 'Lentinula edodes', 'fungus', ARRAY['shiitake mushroom', 'shiitake mushrooms', 'shitake']::text[]),
    ('Button mushroom', 'Agaricus bisporus', 'fungus', ARRAY['white mushroom', 'cremini', 'cremini mushroom', 'baby bella', 'portobello', 'portobello mushroom', 'portabella', 'champignon']::text[]),
    ('Oyster mushroom', 'Pleurotus ostreatus', 'fungus', ARRAY['oyster mushrooms', 'pearl oyster mushroom']::text[]),
    ('Lion''s mane', 'Hericium erinaceus', 'fungus', ARRAY['lions mane', 'lion mane mushroom', 'pom pom mushroom']::text[]),
    ('Chanterelle', 'Cantharellus cibarius', 'fungus', ARRAY['chanterelles', 'golden chanterelle', 'girolle']::text[]),
    ('Porcini', 'Boletus edulis', 'fungus', ARRAY['cep', 'ceps', 'king bolete', 'porcini mushroom']::text[]),
    ('Morel', 'Morchella esculenta', 'fungus', ARRAY['morels', 'morel mushroom', 'yellow morel']::text[]),
    ('Black truffle', 'Tuber melanosporum', 'fungus', ARRAY['truffle', 'Périgord truffle', 'black truffles']::text[]),
    ('Enoki', 'Flammulina velutipes', 'fungus', ARRAY['enoki mushroom', 'enokitake', 'golden needle mushroom']::text[]),
    ('Maitake', 'Grifola frondosa', 'fungus', ARRAY['hen of the woods', 'maitake mushroom', 'ram''s head mushroom']::text[]),
    ('Reishi', 'Ganoderma lucidum', 'fungus', ARRAY['reishi mushroom', 'lingzhi']::text[]),
    ('Nutritional yeast', 'Saccharomyces cerevisiae', 'fungus', ARRAY['nooch', 'brewer''s yeast (food)', 'savory yeast flakes']::text[])
) AS v(common_name, latin_name, category, alternative_names)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.species s
  WHERE lower(trim(s.latin_name)) = lower(trim(v.latin_name))
);
